# Generated by Django 5.2.2 on 2025-07-19 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_created_at_supplier_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (Compra, Devolución, Ajuste Positivo)'), ('OUT', 'Salida (Merma, Uso Interno, Ajuste Negativo)')], help_text='Tipo de movimiento: Entrada o Salida.', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad de unidades que se mueven.', max_digits=10)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del movimiento de stock.')),
                ('description', models.TextField(blank=True, help_text="Notas o razón del movimiento (ej. 'Compra a Proveedor X', 'Merma por producto dañado').", null=True)),
                ('product', models.ForeignKey(help_text='Producto afectado por el movimiento de stock.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Usuario que registró este movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-movement_date', 'product__name'],
            },
        ),
    ]
