# Generated by Django 5.2.2 on 2025-08-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together=set(),
        ),
    ]
